### PR TITLE
_verify: Add Fulcio intermediate certificate

### LINKED ISSUE #109: X509StoreContextError: unable to get local issuer certificate
I noticed this exception raised when running verification:
```
Traceback (most recent call last):
  File "/Users/tetsuo/Code/sigstore-python/env/bin/sigstore", line 8, in <module>
    sys.exit(main())
  File "/Users/tetsuo/Code/sigstore-python/env/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/tetsuo/Code/sigstore-python/env/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/tetsuo/Code/sigstore-python/env/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/tetsuo/Code/sigstore-python/env/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/tetsuo/Code/sigstore-python/env/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/tetsuo/Code/sigstore-python/sigstore/_cli.py", line 299, in _verify
    if verify(
  File "/Users/tetsuo/Code/sigstore-python/sigstore/_verify.py", line 128, in verify
    store_ctx.verify_certificate()
  File "/Users/tetsuo/Code/sigstore-python/env/lib/python3.9/site-packages/OpenSSL/crypto.py", line 1896, in verify_certificate
    raise self._exception_from_context()
OpenSSL.crypto.X509StoreContextError: [20, 0, 'unable to get local issuer certificate']
```
This is trivial to trigger for me. All I need to do is this:
```
$ sigstore sign test_file.txt --output-signature --output-certificate
$ sigstore verify test_file.txt --cert test_file.txt.crt --signature test_file.txt.sig
```
From looking around, the error seems to indicate that we might need to pass the entire certificate chain into verification.

### PR DESCRIPTION
**Pull request by tetsuo-cpp**
Closes #109

### CODE REVIEW

**Comment by woodruffw** [comment]
Hmm, I guess this was part of the prod changes this week? We didn't need an intermediate cert before...

**Review by woodruffw — APPROVED** [review]
LGTM, although @di or @haydentherapper might be able to shed some light on why we need another cert now 🙂

**Review by di — APPROVED** [review]
LGTM. We should probably think a little bit about how this will fail in the future if the intermediate is changed or revoked (until we start using TUF to get these)

**Review by woodruffw — APPROVED** [review]

**Comment by haydentherapper** [comment]
We switched to using off an  intermediate because GCP CA service didn’t support embedding SCTs, so we are now signing with a KMS key

**Comment by woodruffw** [comment]
Thanks for the clarification!

**Pull request merged**
