### PR TITLE
Standardize hashes and version comments in workflows

### LINKED ISSUE #837: Actions inconsistently use hashes, and have incorrect version comment
**Description**

Workflows in the repository don't consistently use hashes, and some of those that _do_ use hashes have incorrect trailing version comments.

Incorrect trailing version comments cause problems with Dependabot's PRs, which fail to update the trailing version comment if the version doesn't match the hash that's being updated. This is a problem that affects one of the PRs that's open at the time of writing: #836. Notice that Dependabot didn't update the version from 2.3.1, which doesn't match the hash that it's attempting to update.

**Version**

N/A

### PR DESCRIPTION
**Pull request by kurtmckee**
Closes #837

#### Summary
While looking at the workflow files I noticed that some actions used versions and others used hashes. I also observed that some actions (like `actions/checkout` in several places) had incorrect version comments (claiming that hash `X` was `v3.3.0`, which was incorrect).

If the version comment is incorrect, Dependabot fails to update it in its PRs. This is evident in a Dependabot PR that is currently open: #836 [fails to update the version comment in `scorecards-analysis.yml`](https://github.com/sigstore/sigstore-python/pull/836/files#diff-43563750699358bcd52e44e9a2700c2e4e9b27512b60dd60c204c4007d3764a9L47-R47).

I *think* that I've followed the contributing guidelines, including opening an issue, linking this PR to that issue, and signing-off the git commit, but please let me know if anything needs to be addressed, or if anything in this PR needs to be addressed. Thanks!

#### Release Note

N/A

#### Documentation

N/A

### CODE REVIEW

**Review by woodruffw — APPROVED** [review]
LGTM, thank you @kurtmckee!

That dependabot auto-update bug is pretty annoying 🙂

**Comment by woodruffw** [comment]
Manually confirmed that all changed hashes are correct.

**Comment by kurtmckee** [comment]
You're welcome! And thank you for double-checking the hashes! :partying_face:

**Pull request merged**
