### PR TITLE
Run tests in CI with full verbosity

### PR DESCRIPTION
**Pull request by di**
[A recent test run](https://github.com/sigstore/sigstore-python/actions/runs/3641503672/jobs/6147515676) seems to have caused a 500-level error with Rekor, but the full certificate that was uploaded in the test was truncated.

This PR ensures CI tests are run with full verbosity so long strings like certificates appear intact in the logs.

### CODE REVIEW

**Comment by jku** [comment]
The output truncation is unfortunate but yes, looks like GitHubOidcPermissionCredentialError.

**Review by tetsuo-cpp — APPROVED** [review]

**Comment by tetsuo-cpp** [comment]
I believe it's because this PR is from a fork rather than a branch. I'm not sure whether there's a way around this.

**Comment by woodruffw** [comment]
> I believe it's because this PR is from a fork rather than a branch. I'm not sure whether there's a way around this.

It's not a good solution, but the trick we use on `gh-action-sigstore-python` is simply to skip tests that require the CI's OIDC credential:

```yaml
    if: (github.event_name != 'pull_request') || !github.event.pull_request.head.repo.fork
```

This would effectively disable the conformance suite on third-party PRs, though.

**Comment by di** [comment]
Reopened as https://github.com/sigstore/sigstore-python/pull/334 to get tests to pass.

**Pull request closed without merging**
