### PR TITLE
cli: deprecate `verify --cert`

### LINKED ISSUE #149: Deprecate the `--cert` alias in favor of `--certificate`
We currently support both, but the former is a legacy alias inherited from the `cosign` CLI.

It violates the symmetry of the rest of the CLI (`--output-signature + --signature` and `--output-certificate` + `--certificate`), so we should deprecate and eventually remove it (probably with 1.0?).

cc @di for thoughts.

### PR DESCRIPTION
**Pull request by woodruffw**
The long form (`--certificate`) is the intended option.

Closes #149.

Signed-off-by: William Woodruff <william@trailofbits.com>

### CODE REVIEW

**Comment by woodruffw** [comment]
As a demo:

```console
$ sigstore verify --cert README.md.crt README.md
WARNING:sigstore._cli:--cert has been replaced with --certificate and will be removed in an upcoming stable release
```

**Comment by tetsuo-cpp** [comment]
Does `cosign` still use `--cert`? I had a quick grep and it looks like it still does.

I'll leave the judgement call to you but I tend to think that it's more important that our CLI is compatible with `cosign` than to be symmetrical or consistent in general.

**Review by tetsuo-cpp — APPROVED** [review]

**Comment by woodruffw** [comment]
> I'll leave the judgement call to you but I tend to think that it's more important that our CLI is compatible with `cosign` than to be symmetrical or consistent in general.

Yeah, that's why I wanted to get @di's opinion -- IMO we're divergent enough at this point that it makes sense to make changes that improve our UX, but this is admittedly a very small example of one of those changes 🙂

**Comment by di** [comment]
I think we should just support both as the same option for now, with no deprecation warning, to ensure this remains intuitive for `cosign` users as well as make sense for new users.

**Comment by woodruffw** [comment]
Very stale and not unanimous, so closing 🙂

**Pull request closed without merging**
