### PR TITLE
oidc: Buildkite support

### PR DESCRIPTION
**Pull request by tetsuo-cpp**
See #31.

### CODE REVIEW

**Comment by tetsuo-cpp** [comment]
I'm running into some errors from Fulcio. Either this hasn't been rolled out yet or I've done something wrong. I also need to:

- [ ] Document functions and types.
- [ ] Add unit tests.

**Comment by di** [comment]
According to the Fulcio maintainers, this hasn't actually been deployed to production yet.

**Comment by tetsuo-cpp** [comment]
> According to the Fulcio maintainers, this hasn't actually been deployed to production yet.

I saw some comments in the PR indicating that it would have been rolled out to staging a few weeks ago, but I'm seeing errors there too. I'm asking around on Slack, let's see what they say.

**Comment by woodruffw** [comment]
BuildKite support was apparently cut with Fulcio 1.1.0, which was today. So we'll hopefully see it on the public instances soon.

**Comment by woodruffw** [comment]
BuildKite support should now be available on both the staging and production instances.

**Comment by tetsuo-cpp** [comment]
This belongs in https://github.com/di/id. Closing.

**Pull request closed without merging**
