### PR TITLE
Update staging-root.json

### PR DESCRIPTION
**Pull request by haydentherapper**
Change hardcoded root to the new root from https://github.com/sigstore/root-signing/pull/756

### CODE REVIEW

**Comment by haydentherapper** [comment]
Note this hasn't been rolled out to staging yet, so it may fail.

**Comment by haydentherapper** [comment]
It'll be ~10 minutes til I update staging

**Comment by haydentherapper** [comment]
Updated the root, please kick off GHA tests again

**Comment by di** [comment]
Still have a lot of test failures here, haven't looked into them yet: https://github.com/sigstore/sigstore-python/actions/runs/4601687825/jobs/8130389601?pr=594

**Comment by haydentherapper** [comment]
A couple notes on things that have changed:
* New root, and we have both a version 1 and 2 of the root. this checks in version 1
* We're now using consistent snapshots, so all target files have a digest prepended to the file name
* We added a delegation for the npm registry
* We added trusted_root.json as another target file
* Same threshold of 1

**Comment by haydentherapper** [comment]
Also I do have a backup of the original TUF repo if need be

**Comment by woodruffw** [comment]
Kicked off the CI again now that this has been deployed.

**Comment by woodruffw** [comment]
> @haydentherapper I've updated the requisite files in https://github.com/trail-of-forks/sigstore-python/tree/ap/wip-staging-root-update, if you'd like to pull from that (I can't update this PR directly because I only have triage perms)

@tnytown Given that this is currently failing the integration tests, I'd say you can go ahead and just create a separate PR rather than trying to coordinate merges between forks here.

**Comment by woodruffw** [comment]
Rolled into #602. Thanks @haydentherapper!

**Pull request closed without merging**
