### PR TITLE
bandit: merge config into pyproject

### PR DESCRIPTION
**Pull request by woodruffw**
Removes another top-level config file.

Signed-off-by: William Woodruff <william@trailofbits.com>

### CODE REVIEW

**Comment by woodruffw** [comment]
CI is currently failing due to a *potential* regression in `pip`; ref https://github.com/pypa/pip/issues/11110

**Review by di — DISMISSED** [review]

**Comment by woodruffw** [comment]
🤦 

```
🔥🔥🔥🔥🔥Running security check🔥🔥🔥🔥🔥🔥
Using config file: pyproject.toml
[main]	ERROR	pyproject.toml : toml parser not available, reinstall with toml extra
b'[main]\tERROR\tpyproject.toml : toml parser not available, reinstall with toml extra\n'
🔥🔥🔥🔥Security check failed🔥🔥🔥🔥
```

**Comment by woodruffw** [comment]
I'll fix this in a moment. I think we should probably just get rid of the third party action (it seems to be a fork of a fork and not actively maintained?) and run `bandit` directly.

**Comment by di** [comment]
Makes sense to me.

**Comment by woodruffw** [comment]
Okay, I made it one of our `dev` deps and mashed it into `make lint` + our main `lint` action.

**Review by di — APPROVED** [review]

**Pull request merged**
