### PR TITLE
ctfe: add staging targets

### PR DESCRIPTION
**Pull request by asraa**
Signed-off-by: Asra Ali <asraa@google.com>

The first is from `curl https://storage.googleapis.com/tuf-root-staging/targets/ctfe_2022.pub`, the second was verbally messaged to me... @haydentherapper I think I got this right.

### CODE REVIEW

**Review by haydentherapper — APPROVED** [review]

**Comment by haydentherapper** [comment]
these are correct

**Comment by haydentherapper** [comment]
We needed to test automation so we did a second sharding.

**Review by woodruffw — APPROVED** [review]

**Comment by haydentherapper** [comment]
@woodruffw You'll also need to update production - https://github.com/sigstore/root-signing/blob/main/targets/ctfe_2022.pub

We're planning to shard tomorrow

**Pull request merged**
