### PR TITLE
Makefile, ci: test Windows, accomodations

### LINKED ISSUE #417: Makefile: Windows compatibility
This is just a reminder to myself: Windows uses `{env}/Scripts` instead of `{env}/bin` for its virtual environment scripts/binaries, so we should tweak the `Makefile` to specialize for that.

### PR DESCRIPTION
**Pull request by woodruffw**
~~WIP, just seeing how annoying this will be.~~

Closes #417.

Signed-off-by: William Woodruff <william@trailofbits.com>

### CODE REVIEW

**Comment by woodruffw** [comment]
Looks like some of the tests are failing on Windows; will investigate.

**Comment by woodruffw** [comment]
This looks like some kind of CRLF weirdness, which doesn't make a lot of sense to me -- the `staging-tuf` test assets should all be LF-only and we should be reading them in binary mode.

**Comment by woodruffw** [comment]
> This looks like some kind of CRLF weirdness, which doesn't make a lot of sense to me -- the `staging-tuf` test assets should all be LF-only and we should be reading them in binary mode.

Confirmed that it's this:

```
    def _fetch(self, url: str) -> Iterator[bytes]:
        filename = os.path.basename(url)
        filepath = _TUF_ASSETS / filename
        if filepath.is_file():
            success[filename] += 1
            content = filepath.read_bytes()
            if filename == "snapshot.json":
>               raise ValueError(len(content))
E               ValueError: 957
```

The actual length is `928`:

```console
$ wc -c test/unit/assets/staging-tuf/snapshot.json 
     928 test/unit/assets/staging-tuf/snapshot.json
```

...however, I still don't understand the "how", unless `read_bytes()` means the exact opposite of what I think it means (return the raw contents, without any platform line normalization).

**Comment by woodruffw** [comment]
This should be good to go, although one of the repo admins is going to need to update the required checks to include the new ones/name changes...

**Review by tetsuo-cpp — DISMISSED** [review]
LGTM!

**Comment by tetsuo-cpp** [comment]
> This should be good to go, although one of the repo admins is going to need to update the required checks to include the new ones/name changes...

@di I think we need you to do this for us. I don't have the permissions for that.

**Comment by tetsuo-cpp** [comment]
> This should be good to go, although one of the repo admins is going to need to update the required checks to include the new ones/name changes...

@di Could you please do this for us? I don't have the permissions for that.

**Comment by di** [comment]
Can we use https://github.com/re-actors/alls-green instead? It's really a pain to make the list of required checks and keep it up to date.

**Comment by woodruffw** [comment]
> Can we use https://github.com/re-actors/alls-green instead? It's really a pain to make the list of required checks and keep it up to date.

Works for me! I can create a PR for that in a little, unless @tetsuo-cpp gets to it first 🙂

**Comment by tetsuo-cpp** [comment]
> Can we use https://github.com/re-actors/alls-green instead? It's really a pain to make the list of required checks and keep it up to date.

Sure, I can make a PR for that now.

**Comment by woodruffw** [comment]
> > Can we use https://github.com/re-actors/alls-green instead? It's really a pain to make the list of required checks and keep it up to date.
> 
> 
> 
> Sure, I can make a PR for that now.
> 
> 
> 
> Edit: Done at #435.

Nice. Let's merge there and update here, and then @di should be able to rid us of the annoying check management once and for all 🙂

**Comment by woodruffw** [comment]
I'll also use this branch to make the `check` names better.

**Comment by woodruffw** [comment]
Looks like the staging instance has degraded a bit more over the past few days...

**Review by di — APPROVED** [review]

**Pull request merged**
